### ISSUE TITLE
smkeys compiliation is broken on M1 Macs

### ISSUE THREAD

**Issue by joe-u410** [spacemeshos/smkeys#1]
The cgo linking for smkeys is currently broken on m1 macs - attempting to build smkeys (and smcli by extension) fails due to the following issue:

`Undefined symbols for architecture arm64:
  "_derive_c", referenced from:
      __cgo_d34415f07b1a_Cfunc_derive_c in 000001.o
     (maybe you meant: __cgo_d34415f07b1a_Cfunc_derive_child_c, __cgo_d34415f07b1a_Cfunc_derive_c )
  "_derive_child_c", referenced from:
      __cgo_d34415f07b1a_Cfunc_derive_child_c in 000001.o
     (maybe you meant: __cgo_d34415f07b1a_Cfunc_derive_child_c)
  "_from_seed_c", referenced from:
      __cgo_d34415f07b1a_Cfunc_from_seed_c in 000001.o
     (maybe you meant: __cgo_d34415f07b1a_Cfunc_from_seed_c)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I'm assuming this is because the referenced dylib was compiled for a non-m1 Mac.

**Comment by joe-u410** [comment]
We've reproduced this on multiple m1 Macbook Pros.

**Comment by joe-u410** [comment]
I'm suspicious this is due to a race condition in the https://github.com/spacemeshos/ed25519_bip32/ release flow, where the dylib for macos-arm64 appears to get deleted and replaced by the dylib for macos-amd64. See attached.

**Comment by lrettig** [comment]
The latest dylib releases on https://github.com/spacemeshos/ed25519_bip32 should resolve this. I can't reproduce the issue; just tested and was able to compile without issue on M1. Reopen if you're still having problems!
